name: fake-service-packer

# This is an example. The Packer GitHub Action
# only works for virtual machines.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate Packer Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: docker.pkr.hcl
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        if [ -f test/unit/requirements.txt ]; then pip install -r test/unit/requirements.txt; fi
    - name: Run unit tests
      run: |
        pytest test/unit